### ISSUE TITLE
CoWorker invitation accepted

### ISSUE THREAD

**Issue by RaiMan** [lipnotic/sikuli-type_alt#2]
LOL, sent the answer to `noreply@...` - so here it is:

Thanks for your work and documentation. I accepted your invitation.

Meanwhile I have revised the Java implementation at least for Windows and the case, that the given character is not found on the current keyboard layout.

But the key-point is, that you must encode the text to type as Unicode: type(u”….“) or with the string encoding method. I guess I have to implement this already on the Python level.

Until now with my German keyboard type(“ä”) does not work, but type(u”ä”) works (on Windows).
The revision in case of not found internally issues the respective ALT-NumPad sequence.

Will be available with the next snapshot.

I will check your module and decide later how I can add it to SikuliX.

Another option, that I will check, is to have an option to select a keyboard-layout with type().

All the best
Raimund

**Comment by lipnotic** [comment]
Welcome Raimund! 👊🏻😉
The type_alt() function bypasses the need for keyboard language settings.
Using your German keyboard type(u“ä”) example, here, with ABNT (layout)/Portuguese(Brazil) language, didn't  work. 
type_alt(u"ä") works fine.
