### ISSUE TITLE
dict_alt has some problems

### ISSUE THREAD

**Issue by RaiMan** [lipnotic/sikuli-type_alt#3]
I made some tests with the dict_alt.

- most of the 3-digit entries do not produce the given character when using ALT-NumPad on a real keyboard.
  Whereas the 4-digit entries seem to work correctly.
```
|dict-char| (ALT-digits) |character produced with type(ALT...) or keyboard|
|√| (251) |¹|
|∞| (236) |ý|
|⌠| (244) |¶|
|⌡| (245) |§|
|Ω| (234) |Û|
|∩| (239) |´|
|≈| (247) |¸|
|≡| (240) |­|
|≤| (243) |¾|
|≥| (242) |‗|
|ⁿ| (252) |³|
|Γ| (226) |Ô|
|Θ| (233) |Ú|
|■| (254) |■|
| | (255) | |
|Σ| (228) |õ|
|Φ| (232) |Þ|
|°| (248) |°|
|α| (224) |Ó|
|±| (241) |±|
|δ| (235) |Ù|
|µ| (230) |µ|
|ε| (238) |¯|
|π| (227) |Ò|
|σ| (229) |Õ|
|τ| (231) |þ|
|φ| (237) |Ý|
```
- ... and 3 of them also have a 4-digit entry (e.g. ß) (only keep the 4-digit entries)

- these 2 entries have a problem:
```
u""":"0147",
u""":"0148",
```
when using the ALT-4digit one gets different apostrophs (seems to be a GitHub/Web problem).
This leads to problems with the dictionary, when downloading the stuff from GitHub.

**Comment by lipnotic** [comment]
I´ve just fixed these ones:
u""":"0147",
u""":"0148",
I´ve just realized there are some "wrong" chars on dictionary. 
Actually, they render different from the dictionaries found on web.
I´ll try to get what´s going on...

**Comment by lipnotic** [comment]
Just updated dictionary from https://theasciicode.com.ar/ascii-codes.txt
Working fine.
